# This is a basic workflow to help you get started with Actions

name: Update Log

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Generate Log
        run: |
          tf=$(mktemp)
          ver=$(python3 gen_log.py "$tf")
          git pull
          git checkout -f auto-docs
          mkdir -p doc
          if ! diff 'doc/更新日志.md' "$tf" > /dev/null; then
            git config user.name 'Bot'
            git config user.email "$(git log -1 --pretty=format:%ae)"
            cp -f "$tf" 'doc/更新日志.md'
            git add 'doc/更新日志.md'
            git commit -m "[Bot] 更新日志 ($ver)"
            git push
          fi
